#!/usr/bin/env python3
"""
Example usage of IPTables Agent

This script demonstrates how to use the iptables_agent library
to parse and explain iptables rules.
"""

from iptables_agent import IPTablesAgent

# Example iptables rules (iptables-save format)
example_rules = """
# Generated by iptables-save
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
-A INPUT -s 192.168.1.0/24 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
"""


def main():
    """Run example demonstrations"""
    
    print("=" * 80)
    print("IPTables Agent - Example Usage")
    print("=" * 80)
    print()
    
    # Create an agent instance
    agent = IPTablesAgent()
    
    # Load rules from string
    print("Loading example iptables rules...")
    rules = agent.load_rules_from_string(example_rules)
    print(f"Loaded {len(rules)} rules\n")
    
    # Explain all rules
    print("Explaining all rules:")
    print("-" * 80)
    explanations = agent.explain_all_rules_formatted()
    print(explanations)
    print()
    
    # Filter by chain
    print("\n" + "=" * 80)
    print("Filtering rules by chain (INPUT only):")
    print("-" * 80)
    input_rules = agent.filter_rules_by_chain('INPUT')
    for i, rule in enumerate(input_rules, 1):
        explanation = agent.explain_rule(rule)
        print(f"{i}. {explanation}")
    print()
    
    # Filter by target
    print("\n" + "=" * 80)
    print("Filtering rules by target (ACCEPT only):")
    print("-" * 80)
    accept_rules = agent.filter_rules_by_target('ACCEPT')
    for i, rule in enumerate(accept_rules, 1):
        explanation = agent.explain_rule(rule)
        print(f"{i}. {explanation}")
    print()
    
    # Show raw rule details
    print("\n" + "=" * 80)
    print("Detailed view of first rule:")
    print("-" * 80)
    if rules:
        rule = rules[0]
        print(f"Chain: {rule.chain}")
        print(f"Target: {rule.target}")
        print(f"Protocol: {rule.protocol}")
        print(f"Source: {rule.source}")
        print(f"Destination: {rule.destination}")
        print(f"State: {rule.state}")
        print(f"Raw: {rule.raw_rule}")
        print(f"\nExplanation: {agent.explain_rule(rule)}")
    
    print("\n" + "=" * 80)
    print("Example complete!")
    print("=" * 80)


if __name__ == '__main__':
    main()
